---
- name: Install i3 packages
  become: yes
  apt: 
    name: "{{ i3_packages }}"
    state: present

- name: Install i3 brightness adjustment
  become: yes
  apt:
    deb: "{{ i3_light_deb }}"
  when: i3_adjustable_brightness

- name: Install i3-workspace-groups
  become: yes
  pip:
    executable: pip3
    name: i3-workspace-groups

- name: Add udev rules
  become: yes
  copy:
    src: files/90-backlight.conf
    dest: /etc/udev/rules.d
  when: i3_adjustable_brightness

- name: Add user to video group
  become: yes
  user:
    name: "{{ admin_user }}"
    groups: video
    append: yes
  when: i3_adjustable_brightness

- name: Install i3 config
  template:
    src: templates/config.j2
    dest: ~/.config/i3/config

- name: Create i3 images dir
  become: yes
  file:
    dest: "{{ i3_images_dir }}"
    state: directory

- name: Add lock binary
  become: yes
  template:
    src: templates/lock.sh
    dest: /usr/local/bin/
    mode: 0755

- name: Add images
  become: yes
  copy:
    src: files/{{ item }}
    dest: "{{ i3_images_dir }}"
  loop:
    - lock.png
    - info.png
    - audio.png
    - clock.png
